---
title: "Project Class in Asset Management"
output: html_notebook
---

### Locale Specification
```{r locale specification}
# set language for dates
os <- Sys.info()["sysname"]

if (os == "Linux") {
  Sys.setlocale("LC_TIME", "en_US.UTF-8")
} else {
  Sys.setlocale("LC_TIME", "English")

  # prevent memory limit problem
  memory.limit(16106 * 3000)
}

# set timezone!
Sys.setenv(TZ = "UCT")
options(scipen = 100)
```

### Import Statement
```{r import statement}
library(dplyr)
library(ggplot2)
library(TTR)
library(quantmod)
library(zoo)
library(corrplot)
library(ModelMetrics)
library(randomForest)
library(lubridate)
```

# Configuration
```{r config}
CONFIG <- list(
  "price_data_dir" = "Price",
  "train_test_data_dir" = "Processed Data",
  "alpha" = 0.038,
  "beta" = 0.24,
  "seed" = 353598215,
  "commission_fee" = 0.001, # 0.0004,  # 0.001,
  "bw" = 5, # Backward Window Size
  "fw" = 2, # Forward Window Size
  "b_lim_sup_window" = 6,
  "f_lim_sup_window" = 6,
  "back_test_start" = "2022-01-1",
  "back_test_end" = "2022-03-31",
  "suffix" = "ncr",
  "stop_loss" = 0.05,
  "balance_algo" = "srs", # 'ncr', 'srs', None
  "loss_func" = "categorical", # 'focal', 'categorical'
  "epochs" = 32 # how many epochs spent in training neural network
)
```

### Data Files
```{r data files}
FILES <- list(
  "SHIB" = "hourly_prices_0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE.csv",
  "UNI" = "hourly_prices_0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984.csv",
  "LINK" = "hourly_prices_0x514910771AF9Ca656af840dff83E8264EcF986CA.csv",
  "WBTC" = "hourly_prices_0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599.csv",
  "MATIC" = "hourly_prices_0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0.csv",
  "VET" = "hourly_prices_0xd850942ef8811f2a866692a623011bde52a462c1.csv",
  "CRO" = "hourly_prices_0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b.csv",
  "MANA" = "hourly_prices_0x0f5d2fb29fb7d3cfee444a200298f468908cc942.csv",
  "GRT" = "hourly_prices_0xc944e90c64b2c07662a292be6244bdf05cda44a7.csv",
  "AAVE" = "hourly_prices_0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9.csv",
  "LEO" = "hourly_prices_0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3.csv",
  "MKR" = "hourly_prices_0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2.csv",
  "CHZ" = "hourly_prices_0x3506424f91fd33084466f402d5d97f05f8e3b4af.csv",
  "ENJ" = "hourly_prices_0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c.csv",
  "AMP" = "hourly_prices_0xff20817765cb7f73d4bde2e66e067e58d11095c2.csv",
  "SAND" = "hourly_prices_0x3845badAde8e6dFF049820680d1F14bD3903a5d0.csv",
  "OMG" = "hourly_prices_0xd26114cd6ee289accf82350c8d8487fedb8a0c07.csv",
  "COMP" = "hourly_prices_0xc00e94cb662c3520282e6f5717214004a7f26888.csv",
  "LRC" = "hourly_prices_0xbbbbca6a901c926f240b89eacb641d8aec7aeafd.csv",
  "CRV" = "hourly_prices_0xD533a949740bb3306d119CC777fa900bA034cd52.csv"
)
```

### Data Collection
```{r collect dataset}
collect.dataset <- function(file, dir, sep = "/") {
  # Combine the directory path and file name
  path <- paste0(getwd(), sep, dir, sep, file)

  # Read the CSV file and omit missing values
  dataset <- read.csv(path)

  # Format time stamp and sort data
  dataset <- dataset %>%
    mutate(hour_timestamp = as.POSIXct(hour_timestamp, format = "%Y-%m-%d %H:%M")) %>%
    arrange(hour_timestamp)

  return(dataset)
}
```

### Feature Extraction
```{r compute oscillator}
compute.oscillator <- function(dataset) {
  dataset <- dataset %>%
    # Close Price Percentage Variation
    mutate(daily_return = ROC(close_price, type = "discrete")) %>%
    # Log Returns
    mutate(log_return = ROC(close_price, type = "continuous")) %>%
    # Z Score
    mutate(z_score = (log_return - runMean(log_return, n = 20)) / runSD(log_return, n = 20)) %>%
    # Relative Strength Index (RSI)
    mutate(rsi = RSI(close_price, n = 14)) %>%
    # Bollinger Bands
    mutate(bbands = BBands(HLC(dataset), n = 20, sd = 2)[, "pctB"]) %>%
    # Ultimate Oscillator
    mutate(ultosc = ultimateOscillator(HLC(dataset), n = c(7, 14, 28))) %>%
    # Price to Moving Average Ratio (Short-Term)
    mutate(pr_ma_ratio_short = (close_price - EMA(close_price, n = 20)) / EMA(close_price, n = 20)) %>%
    # Moving Average Ratio (Short-Term)
    mutate(ma_ratio_short = (EMA(close_price, n = 20) - EMA(close_price, n = 50)) / EMA(close_price, n = 50)) %>%
    # Moving Average Ratio
    mutate(ma_ratio = (EMA(close_price, n = 50) - EMA(close_price, n = 100)) / EMA(close_price, n = 100)) %>%
    # Price to Moving Average Ratio
    mutate(pr_ma_ratio = (close_price - EMA(close_price, n = 50)) / EMA(close_price, n = 50))

  return(dataset)
}
```

```{r compute temporal}
compute.temporal <- function(dataset) {
  dataset <- dataset %>%
    mutate(hour = hour(hour_timestamp)) %>% # TODO: decide if you should divide hour by 4
    mutate(day_of_week = wday(hour_timestamp)) %>%
    mutate(month = month(hour_timestamp))

  return(dataset)
}
```

```{r compute label}
# Labels
BUY <- -1
HOLD <- 0
SELL <- 1

# Close.Prices: An array of closing prices
# BW: Backward Window Size
# FW: Forward Window Size
# Alpha: The alpha is used to establish a low value below which it is not convenient to place a trading order
# Beta: he beta is a high value above which we consider a price variation not influenced by the technical framework but by exogenous forces
compute.label <- function(dataset, bw, fw, alpha, beta) {
  dataset <- dataset %>%
    mutate(ema = EMA(close_price, n = bw)) %>% # Exponential Weighted Moving Average
    mutate(s_1 = lead(close_price, n = fw)) %>%
    mutate(alpha = alpha) %>%
    mutate(beta = beta * (1 + (fw * 0.1))) %>%
    mutate(return = (s_1 - ema) / ema) %>%
    rowwise() %>%
    mutate(label = assign.label(return, alpha, beta))

  return(dataset$label)
}

assign.label <- function(return, alpha, beta) {
  # TODO: check if you should remove this check
  if (is.na(return)) {
    return(HOLD)
  }

  # Check if the absolute value of the return falls within the range [alpha, beta]
  # If this condition is met, then distinguishes between positive and negative returns else return. A positive return labels the time frame as Buy, while a negative return labels the time frame Sell.
  # On the other hand, if the condition is not met, the label is set to Hold to indicate that it is advisable to avoid making any transactions at this time.
  if (abs(return) > alpha && abs(return) < beta) {
    if (return > 0) {
      return(BUY)
    } else {
      return(SELL)
    }
  } else {
    return(HOLD)
  }
}
```

```{r find pattern}
compute.pattern <- function(dataset) {
  return(dataset)
}
```

```{r}
preprocess.filename <- function(file, sep = "/", config = CONFIG) {
  alpha <- config[["alpha"]]
  beta <- config[["beta"]]
  b_lim_sup_window <- config[["b_lim_sup_window"]]
  f_lim_sup_window <- config[["f_lim_sup_window"]]

  dir <- config["price_data_dir"]
  dataset <- collect.dataset(file, dir, sep)
  dataset <- compute.oscillator(dataset)
  dataset <- compute.pattern(dataset)
  dataset <- compute.temporal(dataset)

  labels <- data.frame(hour_timestamp = dataset$hour_timestamp)

  # compute label for the given backward and forward window size
  for (bw in 1:b_lim_sup_window) {
    for (fw in 1:f_lim_sup_window) {
      column_name <- sprintf("lab_%d_%d", bw, fw)
      labels[[column_name]] <- compute.label(dataset, bw, fw, alpha, beta)
    }
  }

  return(list(dataset = dataset, labels = labels))
}
```

```{r}
preprocess <- function(file, sep = "/", omit = TRUE, config = CONFIG) {
  result <- preprocess.filename(file, sep, config)
  dataset <- result$dataset
  labels <- result$labels

  # join labels to dataset
  dataset <- left_join(dataset, labels, by = "hour_timestamp")

  # omit missing values if omit is true
  if (omit) {
    dataset <- dataset %>% na.omit()
  }

  # save file to the train and test data folder
  dir <- CONFIG[["train_test_data_dir"]]
  path <- paste0(getwd(), sep, dir, sep, file)
  write.csv(dataset, path, row.names = FALSE)
}
```


```{r}
# Returns from a single trade operation
# The return of the trade of a cryptocurrency c opened at time t and
# closed at the time frame t + k, is given by:
# fee is the fee applied by the exchange for each trade operation
# close.prices is the closing prices from time t to k
# open.price is the opening price at time t
trade.operation.return <- function(close_prices, open_price, fees) {
  close <- (1 - fees) * close_prices
  open <- (1 + fees) * open_price
  return <- (close - open) / open_price

  return(return)
}
```
